/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes,extraRequire}
 * tslint:disable
 */ 
var styles = ["button[_ngcontent-%COMP%]{\r\n    margin-right: 3rem;\r\n}"];
export { styles as styles };
//# sourceMappingURL=app.component.css.shim.ngstyle.js.map